(defun menu ()
	(terpri)
	(princ "*****  BIENVENIDO  *****")
	(terpri))

(defun askName()
	(terpri)
	(princ "Ingrese su nombre: ")
	(setq name (read-line))
	(with-open-file (stream "archivo.txt" :direction :output :if-exists :append)
		(format stream "~A " name)
	))

(defun askSurname()
	(princ "Ingrese su Apellido: ")
	(setq surname (read-line))
	(with-open-file (stream "archivo.txt" :direction :output :if-exists :append)
		(format stream " ~A " surname)
	))

(defun askEmail()
	(princ "Ingrese su Correo: ")
	(setq email (read-line))
	(with-open-file (stream "archivo.txt" :direction :output :if-exists :append)
		(format stream " ~A~%" email)
	))

(defun printFile()
	(terpri)
	(let ((in (open "archivo.txt" :if-does-not-exist nil)))
		(when in
			(loop for line = (read-line in nil)
				while line do (format t "~a~%" line))
			(close in))
		)
	(terpri))

(defun main()
	(menu)
	(askName)
	(askSurname)
	(askEmail)
	(printFile))


(main)
